"""initial paper schema

Revision ID: 738f0cf2e8f0
Revises: 
Create Date: 2026-09-03 16:57:49.977330
"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '738f0cf2e8f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must precede any Vector column. Autogenerate cannot infer this.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('database', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_name', 'entities', ['name'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pmid', sa.BigInteger(), nullable=False),
    sa.Column('pmcid', sa.String(length=32), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('journal_title', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('fpage', sa.Text(), nullable=True),
    sa.Column('lpage', sa.Text(), nullable=True),
    sa.Column('has_full_text', sa.Boolean(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pmcid'),
    sa.UniqueConstraint('pmid')
    )
    op.create_index('ix_papers_pub_year', 'papers', ['pub_year'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=True),
    sa.Column('given_names', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'ordinal', name='uq_paper_authors_paper_ordinal')
    )
    op.create_index('ix_paper_authors_surname', 'paper_authors', ['surname'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=32), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.CheckConstraint('char_end > char_start', name='ck_paper_chunks_span'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'ordinal', name='uq_paper_chunks_paper_ordinal')
    )
    op.create_index('ix_paper_chunks_paper_span', 'paper_chunks', ['paper_id', 'char_start', 'char_end'], unique=False)
    op.create_index('ix_paper_chunks_section_type', 'paper_chunks', ['section_type'], unique=False)
    # Cosine ANN index. Built on an empty table here, which is the cheap moment;
    # rebuilding after a large backfill would be far slower.
    op.execute(
        "CREATE INDEX ix_paper_chunks_embedding_hnsw ON paper_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('paper_pubtator_docs',
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('paper_references',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('ref_pmid', sa.String(length=32), nullable=True),
    sa.Column('ref_doi', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=16), nullable=True),
    sa.Column('volume', sa.String(length=32), nullable=True),
    sa.Column('fpage', sa.String(length=32), nullable=True),
    sa.Column('lpage', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'ordinal', name='uq_paper_references_paper_ordinal')
    )
    op.create_index('ix_paper_references_ref_pmid', 'paper_references', ['ref_pmid'], unique=False)
    op.create_table('paper_relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('subject_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('object_entity_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'relation_type', 'subject_entity_id', 'object_entity_id', name='uq_paper_relation')
    )
    op.create_index('ix_relations_pair', 'paper_relations', ['subject_entity_id', 'object_entity_id', 'relation_type'], unique=False)
    op.create_index('ix_relations_paper', 'paper_relations', ['paper_id'], unique=False)
    op.create_table('paper_stage_runs',
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.CheckConstraint("stage in ('fetch','chunk','embed','entities','graph')", name='ck_stage_runs_stage'),
    sa.CheckConstraint("status in ('pending','running','done','failed','skipped')", name='ck_stage_runs_status'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'stage')
    )
    op.create_index('ix_stage_runs_stage_status', 'paper_stage_runs', ['stage', 'status'], unique=False)
    op.create_table('paper_entity_mentions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('char_offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('surface_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['paper_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'entity_id', 'char_offset', 'length', name='uq_mention_span')
    )
    op.create_index('ix_mentions_chunk', 'paper_entity_mentions', ['chunk_id'], unique=False)
    op.create_index('ix_mentions_entity', 'paper_entity_mentions', ['entity_id'], unique=False)
    op.create_index('ix_mentions_paper', 'paper_entity_mentions', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_paper_chunks_embedding_hnsw")
    # The vector extension is intentionally left installed: other schemas in
    # this database may depend on it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_paper', table_name='paper_entity_mentions')
    op.drop_index('ix_mentions_entity', table_name='paper_entity_mentions')
    op.drop_index('ix_mentions_chunk', table_name='paper_entity_mentions')
    op.drop_table('paper_entity_mentions')
    op.drop_index('ix_stage_runs_stage_status', table_name='paper_stage_runs')
    op.drop_table('paper_stage_runs')
    op.drop_index('ix_relations_paper', table_name='paper_relations')
    op.drop_index('ix_relations_pair', table_name='paper_relations')
    op.drop_table('paper_relations')
    op.drop_index('ix_paper_references_ref_pmid', table_name='paper_references')
    op.drop_table('paper_references')
    op.drop_table('paper_pubtator_docs')
    op.drop_index('ix_paper_chunks_section_type', table_name='paper_chunks')
    op.drop_index('ix_paper_chunks_paper_span', table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index('ix_paper_authors_surname', table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index('ix_papers_pub_year', table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_entities_name', table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
