"""add paper_chunks.chunk_type

Revision ID: a0ca3165ecb2
Revises: 8c430ca9be25
Create Date: 2026-09-04 10:11:52.598067
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0ca3165ecb2'
down_revision: Union[str, None] = '8c430ca9be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_chunks', sa.Column('chunk_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_chunks', 'chunk_type')
    # ### end Alembic commands ###
