"""users, auth_sessions and free_access_codes

Revision ID: b6d1f0a94c22
Revises: e83b1c47a5d9
Create Date: 2026-09-07 09:40:00.000000

Hand-written rather than autogenerated: the composite foreign keys and the
partial unique index that carry the "anonfree tokens <= activated codes"
invariant are not things autogenerate produces, and the seeded accounts are
data rather than schema.

Both accounts are seeded without a password hash, so no secret is ever
written into a migration. `admin` gets one from POST /admin/create_admin_user
(see the later revision c9e4b71d5f38); `anonfree` is forbidden one by a table
constraint.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b6d1f0a94c22"
down_revision: Union[str, Sequence[str], None] = "e83b1c47a5d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "is_anonymous", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        # Redundant against the primary key, and required as the target of
        # auth_sessions' composite foreign key.
        sa.UniqueConstraint("id", "is_anonymous", name="uq_users_id_is_anonymous"),
        sa.CheckConstraint("NOT (is_admin AND is_anonymous)", name="ck_users_role_exclusive"),
        sa.CheckConstraint(
            "NOT (is_anonymous AND password_hash IS NOT NULL)",
            name="ck_users_anonymous_has_no_password",
        ),
    )

    op.create_table(
        "free_access_codes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activation_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("id", "activated", name="uq_free_access_codes_id_activated"),
        sa.CheckConstraint(
            "activated = (activation_date IS NOT NULL)",
            name="ck_free_access_codes_activation_pair",
        ),
    )

    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("free_access_code_id", sa.BigInteger(), nullable=True),
        sa.Column("code_activated", sa.Boolean(), nullable=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token_hash"),
        # Composite keys, so the two mirrored flags below cannot drift from the
        # rows they mirror -- which is what lets the CHECKs be row-local.
        sa.ForeignKeyConstraint(
            ["user_id", "user_is_anonymous"],
            ["users.id", "users.is_anonymous"],
            name="fk_auth_sessions_user",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["free_access_code_id", "code_activated"],
            ["free_access_codes.id", "free_access_codes.activated"],
            name="fk_auth_sessions_code",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "user_is_anonymous = (free_access_code_id IS NOT NULL)",
            name="ck_auth_sessions_anon_has_code",
        ),
        sa.CheckConstraint(
            "(free_access_code_id IS NULL) = (code_activated IS NULL)",
            name="ck_auth_sessions_code_pair",
        ),
        # With the composite FK above: a session may only reference a code row
        # whose `activated` is true.
        sa.CheckConstraint("code_activated IS NOT FALSE", name="ck_auth_sessions_code_activated"),
    )
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"])
    # One live session per code. Together with the constraints above this is
    # the whole invariant: anonfree can never hold more live tokens than there
    # are activated access codes.
    op.create_index(
        "uq_auth_sessions_live_code",
        "auth_sessions",
        ["free_access_code_id"],
        unique=True,
        postgresql_where=sa.text("free_access_code_id IS NOT NULL AND revoked_at IS NULL"),
    )

    op.execute(
        """
        INSERT INTO users (username, password_hash, is_admin, is_anonymous)
        VALUES ('admin', NULL, true, false),
               ('anonfree', NULL, false, true)
        """
    )


def downgrade() -> None:
    op.drop_index("uq_auth_sessions_live_code", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("free_access_codes")
    op.drop_table("users")
