# Three secrets, filled two different ways on purpose.
#
# The signing key is created here as an *empty container* -- Terraform never
# sees its value, so it never lands in state. You put it in yourself, which is
# what you decided and is the stronger posture.
#
# The datastore credentials are generated by Terraform, because it has to know
# them to create the database and the instance in the first place. Those do
# land in state, which is why the state bucket is encrypted, versioned and
# blocked from public access. Rotate them through the console if the state file
# is ever mishandled.

resource "aws_secretsmanager_secret" "jwt" {
  name                    = "${local.name}/jwt-secret"
  description             = "HS256 key for access tokens. Set the value yourself; Terraform only creates the container."
  recovery_window_in_days = var.destroy_friendly ? 0 : 7
}

resource "random_password" "db" {
  length = 40
  # RDS rejects several punctuation characters in a master password, and a DSN
  # would need them percent-encoded anyway.
  special = false
}

resource "random_password" "neo4j" {
  length  = 40
  special = false
}

# Stored as the whole DSN rather than the password alone: the app takes one
# `DATABASE_URL` string, so composing it here keeps the task definition from
# having to assemble a secret out of parts.
resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${local.name}/database-url"
  recovery_window_in_days = var.destroy_friendly ? 0 : 7
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://${aws_db_instance.main.username}:${random_password.db.result}@${aws_db_instance.main.endpoint}/${aws_db_instance.main.db_name}"
}

# The container reads "user/password", the same shape the app's neo4j_auth
# setting expects, so the server and its clients cannot drift on credentials.
resource "aws_secretsmanager_secret" "neo4j_auth" {
  name                    = "${local.name}/neo4j-auth"
  recovery_window_in_days = var.destroy_friendly ? 0 : 7
}

resource "aws_secretsmanager_secret_version" "neo4j_auth" {
  secret_id     = aws_secretsmanager_secret.neo4j_auth.id
  secret_string = "neo4j/${random_password.neo4j.result}"
}
